#!/usr/bin/perl -w

use strict;

while (<>) {	#take one input line at a time
   chomp;
   if (/((\w+)a)\b/) {
      print "Matched: |$`<$&>$'|\n";	#the special match vars
      print "$1 \n";
   } else {
      print "No match: |$_|\n";
   }
}
