#!/usr/bin/perl -w
## Copyright (C) 2006 by Yours Truly ##

print "Enter radius: ";

$radius=<STDIN>;

if ($radius >= 0) {
   $circumference=2*3.14159*$radius;
   print $circumference."\n";
} else {
   print "Radius entered was less than 0\n";
}
