#!/usr/bin/perl -w
## Copyright (C) 2006 by Yours Truly ##

use strict;

my @fred = qw{ 1 3 5 7 9 };
my $fred_total = &total(@fred);
print "The total of \@fred is $fred_total.\n";


print "The summation from 1-1000 is: ", &total(1..1000),".\n";

sub total {
   my(@input_array)=@_;
   my $sum = 0;
   foreach (@input_array) {
      $sum+=$_;
   }

   return $sum;
}
