#!/usr/bin/perl -w
## Copyright (C) 2006 by Yours Truly ##

use strict;

my @fred = &above_average(1..10);
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";
my @barney = &above_average(100, 1..10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";


sub above_average {
   my @num_list = @_;
   my $sum = 0;
   my @rtrn = ( );

   foreach (@num_list) {
      $sum += $_;
   }

#   print "Sum of numbers is: $sum\n";
   my $avg = $sum/@num_list;
#   print "Avg of numbers is: $avg\n";

   foreach (@num_list) {
      if ($_ > $avg) {
         push @rtrn, $_;
      }
   }

   return @rtrn;
}
